version: "3.8"
services:
    db:
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        image: mariadb:latest
        container_name: mariadb-docker
        ports:
            - ${EXPOSED_DB_PORT}:3306
        environment:
            MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MARIADB_ROOT_USER: ${ROOT_USER}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
          - mariadb-network

networks:
    mariadb-network:
        driver: bridge

# when network is over a VPN environment
# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.10.1.0/24
