CREATE TABLE IF NOT EXISTS customer (
    uuid VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    deleted bool NOT NULL DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS product (
    uuid VARCHAR(36) PRIMARY KEY NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    deleted bool NOT NULL DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS product_order (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_uuid VARCHAR(36) NOT NULL,
    product_uuid VARCHAR(36) NOT NULL,
    product_stock_id INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_uuid)
        REFERENCES customer(uuid)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (product_uuid)
        REFERENCES product(uuid)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS product_stock (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stock DECIMAL(8, 6),
    product_uuid VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_uuid)
        REFERENCES product(uuid)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;
